### PR TITLE
Contribute Polish pronunciation guide

### PR DESCRIPTION
**Pull request by przemub**
Hi Steve,

that's a great project. I'm contributing the Polish guide - please have a look if it's understandable, as a Polish native speaker I may not be the best judge :)

Best,
Prem

### CODE REVIEW

**Comment by enedil** [comment]
Another polish native speaker here. Guide is on spot. The guide lacks however an explanation how to pronounce vowels (this causes issue for English speakers).

**Comment by przemub** [comment]
Thanks for your kind words. I tried to keep it as short-'n'-sweet and possible and focused on parts the English speakers find the most confusing. Do you think a link to a detailed guide like [this](https://en.wikipedia.org/wiki/Help:IPA/Polish) may cover the other sounds?

**Review by SteveMCarroll — APPROVED** [review]
this is wonderful, thank you!   When I was in the Czech republic, a Polish person explained the l with a slash was a "w" sound and it blew my mind and so I was super excited to see this contribution.  thank you!!!   (I'm going to do Czech when I get a spare moment)

**Comment by enedil** [comment]
> Thanks for your kind words. I tried to keep it as short-'n'-sweet and possible and focused on parts the English speakers find the most confusing. Do you think a link to a detailed guide like [this](https://en.wikipedia.org/wiki/Help:IPA/Polish) may cover the other sounds?

Perhaps a general note, that most languages use vowels not as in English, but rather as in Spanish, would suffice.

**Pull request merged**
